apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: S3 Bucket Region Check
    policies.kyverno.io/category: Cloud Security and Best Practices
    policies.nirmata.io/cloudprovider: AWS
    policies.nirmata.io/cloudservice: S3
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: S3 Bucket
    policies.kyverno.io/description: Allow creating S3 bucket in us-west-2 only
  name: s3-bucket-validate-region
spec:
  background: true
  rules:
  - match:
      resources:
        kinds:
        - Bucket
    name: s3-in-us-west-2-only
    validate:
      message: location {{ request.object.spec.forProvider.region }} is not allowed
      pattern:
        spec:
          forProvider:
            locationConstraint: us-west-2
  validationFailureAction: Enforce
